INSERT INTO STORE_T (NAME, OWNER, OPEN) VALUES ('Joe''s Sports Store', 'Joe', true);

INSERT INTO ORDER_T (ID, PRODUCT_ID) VALUES(ORDER_SEQ.nextval, 1);

INSERT INTO PRODUCT_T (NAME) VALUES('Basketball');
