CREATE TABLE PRODUCT_T (
  ID IDENTITY PRIMARY KEY,
  NAME VARCHAR(120),
  QTY SMALLINT,
  BACKORDER_AVAILABLE VARCHAR(1)
);

CREATE TABLE STORE_T (
  NAME VARCHAR(120),
  OWNER VARCHAR(40),
  OPEN VARCHAR(20),
  WEBSITE VARCHAR(120),
  ADDR_LINE1 VARCHAR(120),
  ADDR_CITY VARCHAR(120),
  ADDR_ST VARCHAR(30),
  ADDR_POST_CD VARCHAR(12),
  PRIMARY KEY (NAME, OWNER)
);

CREATE TABLE ORDER_T (
  ID BIGINT PRIMARY KEY,
  TOTAL DECIMAL(19,2),
  CREATE_DT TIMESTAMP,
  VERSION SMALLINT
);

CREATE SEQUENCE ORDER_SEQ START WITH 1 INCREMENT BY 1;  
  