CREATE TABLE PRODUCT_T (
  ID IDENTITY PRIMARY KEY,
  NAME VARCHAR(120),
  QTY SMALLINT,
  BACKORDER_AVAILABLE VARCHAR(1)
);

CREATE TABLE STORE_T (
  NAME VARCHAR(120),
  OWNER VARCHAR(40),
  OPEN VARCHAR(20),
  WEBSITE VARCHAR(120),
  PRIMARY KEY (NAME, OWNER)
);

CREATE TABLE ORDER_T (
  ID BIGINT PRIMARY KEY,
  TOTAL DECIMAL(19,2),
  CREATE_DT TIMESTAMP,
  VERSION SMALLINT
);

CREATE SEQUENCE ORDER_SEQ START WITH 1 INCREMENT BY 1;  

CREATE TABLE CUSTOMER_T (
  ID IDENTITY PRIMARY KEY,
  USERNAME VARCHAR(20),
  FIRST_NAME VARCHAR(40),
  LAST_NAME VARCHAR(40)
);
